### ISSUE TITLE
O S D I

### ISSUE THREAD

**Issue by joshco** [highfalutin/com.lemniscus.casedatecascade#1]
If you're for real, are an advocate of democratic standards like HTML, CSS, HTTP, and think the progressive tech ecosystem should be fair and level, I'd ask for an audience with the civi core team and or those with a passion for equal treatment for LGBTs, and anti-trust.

please hit me up via the contact info on my GH profile.  
What would you say the most subtle difference in the declarations of the following two functions is?
_casedatecascade_civix_civicrm_config
_casedatecascade_civix_civicrm_xmlMenu

**Comment by highfalutin** [comment]
Hi Josh, if you're interested in this "Case Date Cascade" extension, unfortunately I never finished it, and haven't looked at it in years. The functions you ask about are automatically generated by the civix extension-building tool.

I'm afraid I don't have any special access to the Civi core team, but you can always reach out to them through the same channels as everyone else (see https://civicrm.org/help). It does sound like we share the values that you mention, so I wish you good luck.
